# Generated by Django 5.2.4 on 2025-08-05 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now

# ...

migrations.AddField(
    model_name='goal',
    name='deadline',
    field=models.DateTimeField(default=now, verbose_name='Дата окончания'),
    preserve_default=False,
),

migrations.AddField(
    model_name='studysession',
    name='end_date',
    field=models.DateTimeField(default=now, verbose_name='Дата сессии'),
    preserve_default=False,
),

migrations.AddField(
    model_name='studysession',
    name='start_time',
    field=models.DateTimeField(default=now, verbose_name='Дата создания'),
    preserve_default=False,
),



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Категория материала',
                'verbose_name_plural': 'Категории материалов',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='studysession',
            name='end_date',
            field=models.DateTimeField(default=now, verbose_name='Дата сессии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(default=now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Учебный материал',
                'verbose_name_plural': 'Учебные материалы',
            },
        ),
    ]
