# Generated by Django 5.2.4 on 2025-08-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterialcategory',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='title',
        ),
        migrations.AddField(
            model_name='achievement',
            name='code',
            field=models.CharField(default='default_code', max_length=50, unique=True, verbose_name='Код условия'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='studymaterialcategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FavoriteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный материал',
                'verbose_name_plural': 'Избранные материалы',
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по теме',
                'verbose_name_plural': 'Прогресс по темам',
            },
        ),
    ]
