# Generated by Django 5.2.4 on 2025-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_goal_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
