# Generated by Django 5.2.4 on 2025-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studymaterialcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
