# Generated by Django 5.2.4 on 2025-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studymaterial_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterialcategory',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='topic',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
