# Generated by Django 5.2.4 on 2025-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studymaterial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
