# Generated by Django 5.2.4 on 2025-08-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_goal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
