# Generated by Django 5.2.4 on 2025-08-07 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_goal_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-date'], 'verbose_name': 'Учебная сессия', 'verbose_name_plural': 'Учебные сессии'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Категория', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.CharField(default='Категория', max_length=100, verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Длительность в минутах', null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='goal',
            field=models.TextField(verbose_name='Цель занятия'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='note',
            field=models.TextField(blank=True, default='Категория', verbose_name='Заметка'),
            preserve_default=False,
        ),
    ]
