# Generated by Django 5.2.4 on 2025-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_studysession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель занятия'),
        ),
    ]
