# Generated by Django 5.2.4 on 2025-08-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_studysession_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
