# Generated by Django 5.2.4 on 2025-08-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xp',
        ),
    ]
